In [ ]:
!pip ins

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_excel(r"C:\Users\DELL\Downloads\Financial_Sample.xlsx")

In [5]:
df.shape

(700, 16)

In [6]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

In [7]:
df=df.bfill()

In [8]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [9]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='str')

In [10]:
df=df.drop(columns=["Date",'Month Name'])

# encode all the text/str columns into numerical for ML

# 1. Onehot encoding-
        canada germany france
        1       0        0
        0       1        0
        0       0         1
2. Ordinal encoding-
        S=0,M=1,XL=2,XXL=3
3. Label encoding-
    M-1 F-0

In [14]:
newdf=df.copy()

In [30]:
for col in df.select_dtypes(include="str").columns:
    df[col]=df[col].map(lambda var:list(df[col].unique()).index(var))

In [31]:
list(df["Segment"].unique())

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    int64
 1   Country              700 non-null    int64
 2   Product              700 non-null    int64
 3   Discount Band        700 non-null    int64
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    float64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Month Number         700 non-null    int64
 13  Year                 700 non-null    int64
dtypes: float64(7), int64(7)
memory usage: 76.7 KB

In [33]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Year
0,0,0,0,0,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,1,2014
1,0,1,0,0,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,1,2014

In [36]:
newwdf=newdf.copy()

In [38]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Year
0,0,0,0,0,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,1,2014
1,0,1,0,0,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,1,2014