In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_excel(r"C:\Users\DELL\Downloads\Financial_Sample.xlsx")

In [4]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le=LabelEncoder()

In [9]:
for col in df.select_dtypes(include="str").columns:
    df[col]=le.fit_transform(df[col])

In [11]:
df.head(5)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,2,0,1,3,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,4,2014
1,2,2,1,3,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,4,2014
2,3,1,1,3,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,6,2014
3,3,2,1,3,888.0,3,15.0,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,6,2014
4,3,3,1,3,2470.0,3,15.0,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,6,2014

In [12]:
# Ordinal encoder

In [14]:
newdf=df.copy()

In [15]:
newdf

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,2,0,1,3,1618.5,3,20.0,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,4,2014
1,2,2,1,3,1321.0,3,20.0,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,4,2014
2,3,1,1,3,2178.0,3,15.0,32670.0,0.00,32670.00,21780.0,10890.00,2014-06-01,6,6,2014
3,3,2,1,3,888.0,3,15.0,13320.0,0.00,13320.00,8880.0,4440.00,2014-06-01,6,6,2014
4,3,3,1,3,2470.0,3,15.0,37050.0,0.00,37050.00,24700.0,12350.00,2014-06-01,6,6,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,4,1,0,0,2475.0,260,300.0,742500.0,111375.00,631125.00,618750.0,12375.00,2014-03-01,3,7,2014
696,4,3,0,0,546.0,260,300.0,163800.0,24570.00,139230.00,136500.0,2730.00,2014-10-01,10,10,2014
697,2,3,2,0,1368.0,5,7.0,9576.0,1436.40,8139.60,6840.0,1299.60,2014-02-01,2,3,2014
698,2,0,3,0,723.0,10,7.0,5061.0,759.15,4301.85,3615.0,686.85,2014-04-01,4,0,2014
699,0,4,4,0,1806.0,250,12.0,21672.0,3250.80,18421.20,5418.0,13003.20,2014-05-01,5,8,2014

In [16]:
old_df=df.copy()

In [17]:
old_df.head(3)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,2,0,1,3,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,4,2014
1,2,2,1,3,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,4,2014
2,3,1,1,3,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,6,2014