In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_excel(r"C:\Users\DELL\Downloads\Financial_Sample.xlsx")

In [4]:
df.shape

(700, 16)

In [5]:
df.head(3)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014

In [7]:
df[["Sale Price","Gross Sales"]].describe()

       Sale Price   Gross Sales
count  693.000000  6.950000e+02
mean   117.914863  1.839670e+05
std    136.571680  2.547749e+05
min      7.000000  1.799000e+03
25%     12.000000  1.760250e+04
50%     20.000000  3.838500e+04
75%    300.000000  2.859500e+05
max    350.000000  1.207500e+06

In [10]:
# Standardization
# mean=0,std=1
#z=(x-miu(mean))/sigma

In [13]:
li=['Sale Price','Gross Sales']
for col in li:
    df[col]=(df[col]-df[col].mean())/df[col].std()

In [14]:
df[["Sale Price","Gross Sales"]].describe()

         Sale Price   Gross Sales
count  6.930000e+02  6.950000e+02
mean   6.151885e-17  7.667727e-18
std    1.000000e+00  1.000000e+00
min   -8.121366e-01 -7.150157e-01
25%   -7.755258e-01 -6.529864e-01
50%   -7.169485e-01 -5.714144e-01
75%    1.333257e+00  4.002865e-01
max    1.699365e+00  4.017401e+00

In [15]:
df=pd.read_excel(r"C:\Users\DELL\Downloads\Financial_Sample.xlsx")

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc=StandardScaler()

In [19]:
sc

StandardScaler()

In [20]:
sc.fit_transform(df[['Sale Price','Gross Sales']])

array([[-0.71746635, -0.59545203],
       [-0.71746635, -0.6188228 ],
       [-0.75410361, -0.59427367],
       ...,
       [-0.81272322, -0.68498368],
       [-0.81272322, -0.70271797],
       [-0.77608596, -0.63747228]], shape=(700, 2))

In [23]:
output=pd.DataFrame(sc.fit_transform(df[['Sale Price','Gross Sales']]),columns=['Sale Price','Gross Sales'])

In [24]:
output.describe()

         Sale Price   Gross Sales
count  6.930000e+02  6.950000e+02
mean   4.357585e-17  1.725239e-17
std    1.000722e+00  1.000720e+00
min   -8.127232e-01 -7.155307e-01
25%   -7.760860e-01 -6.534567e-01
50%   -7.174664e-01 -5.718260e-01
75%    1.334220e+00  4.005748e-01
max    1.700592e+00  4.020295e+00

In [25]:
# Normalization
#convert all values from 0 to 1
#n=X-Xmin/Xmax-Xmin

In [26]:
li=['Sale Price','Gross Sales']

In [30]:
for col in li:
    df[col]=(df[col]-df[col].min())/(df[col].max()-df[col].min())

In [31]:
df[['Sale Price','Gross Sales']].describe()

       Sale Price  Gross Sales
count  693.000000   695.000000
mean     0.323367     0.151089
std      0.398168     0.211309
min      0.000000     0.000000
25%      0.014577     0.013107
50%      0.037901     0.030344
75%      0.854227     0.235673
max      1.000000     1.000000

In [32]:
from sklearn.preprocessing import MinMaxScaler

In [33]:
scaler=MinMaxScaler()

In [34]:
scaler.fit_transform(df[['Sale Price','Gross Sales']])

array([[0.03790087, 0.02535537],
       [0.03790087, 0.02042049],
       [0.02332362, 0.02560419],
       ...,
       [0.        , 0.00645019],
       [0.        , 0.00270548],
       [0.01457726, 0.01648253]], shape=(700, 2))